### ISSUE TITLE
[CS1061] 'PlayerLoginPage' does not contain a definition for 'AnimateOut' and no accessible extension method 'AnimateOut' accepting a first argument of type 'PlayerLoginPage' could be found

### ISSUE THREAD

**Issue by owlvano** [dtschatrix/VaporwavePlayer#4]
The class PlayerLoginPage doesn't have an AnimateOut method.

![image](https://user-images.githubusercontent.com/17502982/65165207-ff760000-da46-11e9-8c7f-8f39479052c8.png)

**Comment by dtschatrix** [comment]
code behind issue gonna fix it on next update
